Accept link attributes without quote such as rel=next
The scanner was already setup to match the pattern, but there's an unnecessary gsub call in case of the match and caused runtime error such as:

    irb(main):002:0> LinkHeader.parse('</path>; rel=next')
    NoMethodError: undefined method `gsub' for nil:NilClass
            from {...}lib/ruby/gems/2.0.0/gems/link_header-0.0.7/lib/link_header.rb:94:in `parse'

This patch moves the gsub to only run in case of quoted match.